import { readFile, writeFile } from "node:fs/promises";
import { join, sep } from "node:path";

// SavedVariables live at <game>\WTF\Account\<acct>\SavedVariables\Guilded.lua,
// and the addon at <game>\Interface\AddOns\Guilded. `standingsFile` in
// companion.config.json overrides this if the layout is different.
export function resolveStandingsPath(config) {
  if (config.standingsFile) return config.standingsFile;
  const parts = config.watchFile.split(/[\\/]/);
  const wtf = parts.findIndex((part) => part.toLowerCase() === "wtf");
  if (wtf < 1) return null;
  return join(parts.slice(0, wtf).join(sep) || sep, "Interface", "AddOns", "Guilded", "Standings.lua");
}

function luaString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/[\r\n]/g, " ")}"`;
}

export function standingsToLua(data) {
  const rows = data.standings.map((row) =>
    `    { name = ${luaString(row.character)}, ep = ${Math.trunc(row.ep)}, gp = ${Math.trunc(row.gp)}, main = ${row.main ? "true" : "false"} },`
  );
  return [
    "-- Generated by the Guilded companion from the Discord bot. Overwritten",
    "-- automatically; edits here are lost.",
    "GuildedStandings = {",
    `  updatedAt = ${luaString(data.updatedAt)},`,
    // PR = EP / (GP + baseGp); the addon recomputes PR with this.
    `  baseGp = ${Math.max(0, Math.trunc(data.baseGp ?? 0))},`,
    "  players = {",
    ...rows,
    "  }",
    "}",
    "",
    "-- Dungeon runs the bot has stored; the addon marks these as synced.",
    "GuildedDungeonAccepted = {",
    ...(data.acceptedRunRefs ?? []).map((ref) => `  ${luaString(ref)},`),
    "}",
    "",
    "-- Dungeon points this season (top 10), for the addon's Dungeons tab.",
    ...(data.dungeonBoard ? [
      `GuildedDungeonBoard = { season = ${luaString(data.dungeonBoard.season)}, rows = {`,
      ...data.dungeonBoard.rows.map((row) => `  { name = ${luaString(row.name)}, points = ${Math.trunc(row.points)} },`),
      "} }"
    ] : ["GuildedDungeonBoard = nil"]),
    "",
    "-- The next raid's signed-up players (main characters), for /guilded invite raid.",
    ...(data.nextRaid ? [
      `GuildedNextRaid = { id = ${luaString(data.nextRaid.id)}, title = ${luaString(data.nextRaid.title)}, at = ${luaString(data.nextRaid.scheduledAt)}, core = ${luaString(data.nextRaid.core ?? "")}, players = {`,
      ...data.nextRaid.players.map((player) => `  { name = ${luaString(player.name)}, role = ${luaString(player.role)} },`),
      "}, maybe = {",
      ...(data.nextRaid.maybe ?? []).map((name) => `  ${luaString(name)},`),
      "} }"
    ] : ["GuildedNextRaid = nil"]),
    ""
  ].join("\n");
}

export async function writeStandings(config) {
  const path = resolveStandingsPath(config);
  if (!path) throw new Error("Could not find the AddOns folder from watchFile; set standingsFile in companion.config.json.");
  const url = new URL("/api/v1/standings", config.uploadUrl);
  url.searchParams.set("guild", config.guildDiscordId);
  const response = await fetch(url, { headers: { authorization: `Bearer ${config.uploadToken}` } });
  const body = await response.json();
  if (!response.ok) throw new Error(`Standings request failed (${response.status}): ${body.error}`);
  const text = standingsToLua(body);
  // The timestamp changes every call; compare the rest so an unchanged table
  // does not rewrite the file (the game only reads it on reload anyway).
  const body2 = (value) => value.replace(/updatedAt = "[^"]*",/, "");
  let unchanged = false;
  try { unchanged = body2(await readFile(path, "utf8")) === body2(text); } catch { unchanged = false; }
  if (!unchanged) await writeFile(path, text, "utf8");
  return { path, count: body.standings.length, unchanged };
}
